---
name: format
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  format:
    runs-on: ubuntu-latest
    env:
      SAFE_CHAIN_MINIMUM_PACKAGE_AGE_HOURS: 168 # 7日
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ secrets.PROJECT_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.PROJECT_AUTOMATION_PRIVATE_KEY }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          persist-credentials: false
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          bun-version-file: .bun-version
      - name: Install
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        run: |
          curl -fsSL https://raw.githubusercontent.com/AikidoSec/safe-chain/main/install-scripts/install-safe-chain.sh | sh -s -- --ci
          bun install
      - run: bunx prettier --write .
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
      - run: bun run build
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
      - uses: dev-hato/actions-diff-pr-management@571be0d9572aaf77cdd315c12d6e73a1112910d7 # v2.2.6
        with:
          github-token: ${{steps.generate_token.outputs.token}}
          branch-name-prefix: fix-format
          pr-title-prefix: Fix format
          pr-description-prefix: CI fixed format.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
